# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embedding_service_pb2 as embedding__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """The embedding service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedHybrid = channel.unary_unary(
                '/embedding.EmbeddingService/EmbedHybrid',
                request_serializer=embedding__service__pb2.EmbedQueryRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedHybridResponse.FromString,
                _registered_method=True)
        self.EmbedHybridDocuments = channel.unary_unary(
                '/embedding.EmbeddingService/EmbedHybridDocuments',
                request_serializer=embedding__service__pb2.EmbedDocumentsRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedHybridDocumentsResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """The embedding service definition
    """

    def EmbedHybrid(self, request, context):
        """Embed query with hybrid embedding (dense + sparse + colbert)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedHybridDocuments(self, request, context):
        """Embed documents with hybrid embedding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedHybrid': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedHybrid,
                    request_deserializer=embedding__service__pb2.EmbedQueryRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedHybridResponse.SerializeToString,
            ),
            'EmbedHybridDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedHybridDocuments,
                    request_deserializer=embedding__service__pb2.EmbedDocumentsRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedHybridDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """The embedding service definition
    """

    @staticmethod
    def EmbedHybrid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/EmbedHybrid',
            embedding__service__pb2.EmbedQueryRequest.SerializeToString,
            embedding__service__pb2.EmbedHybridResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedHybridDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/EmbedHybridDocuments',
            embedding__service__pb2.EmbedDocumentsRequest.SerializeToString,
            embedding__service__pb2.EmbedHybridDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
