"""create core tables

Revision ID: b92ab8d728b4
Revises: 
Create Date: 2026-07-10 02:41:00.451542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b92ab8d728b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('poi_id', sa.String(), nullable=False),
    sa.Column('poi_name', sa.Text(), nullable=False),
    sa.Column('poi_name_norm', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('brand_norm', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_norm', sa.Text(), nullable=True),
    sa.Column('sub_category', sa.Text(), nullable=True),
    sa.Column('sub_category_norm', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_norm', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('district_norm', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_norm', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('opening_hours_raw', sa.Text(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('opening_hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_norm', sa.Text(), nullable=True),
    sa.Column('semantic_text', sa.Text(), nullable=True),
    sa.Column('keyword_text', sa.Text(), nullable=True),
    sa.Column('enrichment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('poi_id')
    )
    op.create_index('idx_pois_category_norm', 'pois', ['category_norm'], unique=False)
    op.create_index('idx_pois_city_norm', 'pois', ['city_norm'], unique=False)
    op.create_index('idx_pois_district_norm', 'pois', ['district_norm'], unique=False)
    op.create_index('idx_pois_is_24_7', 'pois', ['is_24_7'], unique=False)
    op.create_index('idx_pois_open_close_time', 'pois', ['open_time', 'close_time'], unique=False)
    op.create_index('idx_pois_popularity', 'pois', ['popularity_score'], unique=False)
    op.create_index('idx_pois_price_level', 'pois', ['price_level'], unique=False)
    op.create_index('idx_pois_rating', 'pois', ['rating'], unique=False)
    op.create_table('taxonomy_aliases',
    sa.Column('alias_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('alias_norm', sa.Text(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_norm', sa.Text(), nullable=False),
    sa.Column('target_display', sa.Text(), nullable=True),
    sa.Column('constraint_default', sa.String(), nullable=False),
    sa.Column('is_hard_capable', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('alias_type', 'alias_norm', 'target_id', name='uq_taxonomy_alias_unique')
    )
    op.create_index('idx_taxonomy_alias_norm', 'taxonomy_aliases', ['alias_norm'], unique=False)
    op.create_index('idx_taxonomy_alias_type', 'taxonomy_aliases', ['alias_type'], unique=False)
    op.create_index('idx_taxonomy_target', 'taxonomy_aliases', ['target_id'], unique=False)
    op.create_table('poi_search_documents',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('poi_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_norm', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('qdrant_collection', sa.String(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(), nullable=True),
    sa.Column('embedding_version', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.poi_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('idx_poi_search_documents_poi', 'poi_search_documents', ['poi_id'], unique=False)
    op.create_index('idx_poi_search_documents_qdrant_point', 'poi_search_documents', ['qdrant_point_id'], unique=False)
    op.create_index('idx_poi_search_documents_type', 'poi_search_documents', ['doc_type'], unique=False)
    op.create_table('poi_signals',
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('poi_id', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_name', sa.Text(), nullable=False),
    sa.Column('signal_norm', sa.Text(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_rankable', sa.Boolean(), nullable=False),
    sa.Column('constraint_default', sa.String(), nullable=False),
    sa.Column('rank_behavior', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.poi_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id'),
    sa.UniqueConstraint('poi_id', 'signal_type', 'signal_norm', 'source', name='uq_poi_signal_unique')
    )
    op.create_index('idx_poi_signals_filterable', 'poi_signals', ['is_filterable'], unique=False)
    op.create_index('idx_poi_signals_norm', 'poi_signals', ['signal_norm'], unique=False)
    op.create_index('idx_poi_signals_poi', 'poi_signals', ['poi_id'], unique=False)
    op.create_index('idx_poi_signals_rankable', 'poi_signals', ['is_rankable'], unique=False)
    op.create_index('idx_poi_signals_type_norm', 'poi_signals', ['signal_type', 'signal_norm'], unique=False)
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pois_name_trgm ON pois USING GIN (poi_name_norm gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pois_brand_trgm ON pois USING GIN (brand_norm gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pois_address_trgm ON pois USING GIN (address_norm gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pois_keyword_trgm ON pois USING GIN (keyword_text gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_poi_signals_norm_trgm ON poi_signals USING GIN (signal_norm gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_taxonomy_alias_norm_trgm ON taxonomy_aliases USING GIN (alias_norm gin_trgm_ops)"
    )

    op.drop_index(op.f('idx_vocab_aliases'), table_name='vocabulary', postgresql_using='gin')
    op.drop_index(op.f('idx_vocab_concept'), table_name='vocabulary')
    op.drop_index(op.f('idx_vocab_kind'), table_name='vocabulary')
    op.drop_index(op.f('vocabulary_kind_canonical_key'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('idx_poi_brand'), table_name='poi')
    op.drop_index(op.f('idx_poi_category'), table_name='poi')
    op.drop_index(op.f('idx_poi_city_dist'), table_name='poi')
    op.drop_index(op.f('idx_poi_concepts'), table_name='poi', postgresql_ops={'concepts': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_poi_open_end'), table_name='poi')
    op.drop_index(op.f('idx_poi_pop'), table_name='poi')
    op.drop_index(op.f('idx_poi_price'), table_name='poi')
    op.drop_index(op.f('idx_poi_rating'), table_name='poi')
    op.drop_table('poi')
    op.drop_table('signals')
    op.drop_table('_prisma_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS idx_taxonomy_alias_norm_trgm")
    op.execute("DROP INDEX IF EXISTS idx_poi_signals_norm_trgm")
    op.execute("DROP INDEX IF EXISTS idx_pois_keyword_trgm")
    op.execute("DROP INDEX IF EXISTS idx_pois_address_trgm")
    op.execute("DROP INDEX IF EXISTS idx_pois_brand_trgm")
    op.execute("DROP INDEX IF EXISTS idx_pois_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_poi_signals_type_norm', table_name='poi_signals')
    op.drop_index('idx_poi_signals_rankable', table_name='poi_signals')
    op.drop_index('idx_poi_signals_poi', table_name='poi_signals')
    op.drop_index('idx_poi_signals_norm', table_name='poi_signals')
    op.drop_index('idx_poi_signals_filterable', table_name='poi_signals')
    op.drop_table('poi_signals')
    op.drop_index('idx_poi_search_documents_type', table_name='poi_search_documents')
    op.drop_index('idx_poi_search_documents_qdrant_point', table_name='poi_search_documents')
    op.drop_index('idx_poi_search_documents_poi', table_name='poi_search_documents')
    op.drop_table('poi_search_documents')
    op.drop_index('idx_taxonomy_target', table_name='taxonomy_aliases')
    op.drop_index('idx_taxonomy_alias_type', table_name='taxonomy_aliases')
    op.drop_index('idx_taxonomy_alias_norm', table_name='taxonomy_aliases')
    op.drop_table('taxonomy_aliases')
    op.drop_index('idx_pois_rating', table_name='pois')
    op.drop_index('idx_pois_price_level', table_name='pois')
    op.drop_index('idx_pois_popularity', table_name='pois')
    op.drop_index('idx_pois_open_close_time', table_name='pois')
    op.drop_index('idx_pois_is_24_7', table_name='pois')
    op.drop_index('idx_pois_district_norm', table_name='pois')
    op.drop_index('idx_pois_city_norm', table_name='pois')
    op.drop_index('idx_pois_category_norm', table_name='pois')
    op.drop_table('pois')
    # ### end Alembic commands ###
