# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65mbedding_service.proto\x12\tembedding\"0\n\x11\x45mbedQueryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"5\n\x15\x45mbedDocumentsRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\r\n\x05model\x18\x02 \x01(\t\"\x85\x02\n\x13\x45mbedHybridResponse\x12\x14\n\x0c\x64\x65nse_vector\x18\x01 \x03(\x02\x12I\n\x0esparse_weights\x18\x02 \x03(\x0b\x32\x31.embedding.EmbedHybridResponse.SparseWeightsEntry\x12/\n\x0f\x63olbert_vectors\x18\x03 \x03(\x0b\x32\x16.embedding.FloatVector\x12\r\n\x05model\x18\x04 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x05 \x01(\x02\x1a\x34\n\x12SparseWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"v\n\x1c\x45mbedHybridDocumentsResponse\x12.\n\nembeddings\x18\x01 \x03(\x0b\x32\x1a.embedding.HybridEmbedding\x12\r\n\x05model\x18\x02 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\x02\"\x1d\n\x0b\x46loatVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\xd5\x01\n\x0fHybridEmbedding\x12\x14\n\x0c\x64\x65nse_vector\x18\x01 \x03(\x02\x12\x45\n\x0esparse_weights\x18\x02 \x03(\x0b\x32-.embedding.HybridEmbedding.SparseWeightsEntry\x12/\n\x0f\x63olbert_vectors\x18\x03 \x03(\x0b\x32\x16.embedding.FloatVector\x1a\x34\n\x12SparseWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\xc6\x01\n\x10\x45mbeddingService\x12M\n\x0b\x45mbedHybrid\x12\x1c.embedding.EmbedQueryRequest\x1a\x1e.embedding.EmbedHybridResponse\"\x00\x12\x63\n\x14\x45mbedHybridDocuments\x12 .embedding.EmbedDocumentsRequest\x1a\'.embedding.EmbedHybridDocumentsResponse\"\x00\x42G\n\x15\x63om.example.embeddingB\x0e\x45mbeddingProtoP\x01Z\x1cgithub.com/example/embeddingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.example.embeddingB\016EmbeddingProtoP\001Z\034github.com/example/embedding'
  _globals['_EMBEDHYBRIDRESPONSE_SPARSEWEIGHTSENTRY']._loaded_options = None
  _globals['_EMBEDHYBRIDRESPONSE_SPARSEWEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_HYBRIDEMBEDDING_SPARSEWEIGHTSENTRY']._loaded_options = None
  _globals['_HYBRIDEMBEDDING_SPARSEWEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_EMBEDQUERYREQUEST']._serialized_start=38
  _globals['_EMBEDQUERYREQUEST']._serialized_end=86
  _globals['_EMBEDDOCUMENTSREQUEST']._serialized_start=88
  _globals['_EMBEDDOCUMENTSREQUEST']._serialized_end=141
  _globals['_EMBEDHYBRIDRESPONSE']._serialized_start=144
  _globals['_EMBEDHYBRIDRESPONSE']._serialized_end=405
  _globals['_EMBEDHYBRIDRESPONSE_SPARSEWEIGHTSENTRY']._serialized_start=353
  _globals['_EMBEDHYBRIDRESPONSE_SPARSEWEIGHTSENTRY']._serialized_end=405
  _globals['_EMBEDHYBRIDDOCUMENTSRESPONSE']._serialized_start=407
  _globals['_EMBEDHYBRIDDOCUMENTSRESPONSE']._serialized_end=525
  _globals['_FLOATVECTOR']._serialized_start=527
  _globals['_FLOATVECTOR']._serialized_end=556
  _globals['_HYBRIDEMBEDDING']._serialized_start=559
  _globals['_HYBRIDEMBEDDING']._serialized_end=772
  _globals['_HYBRIDEMBEDDING_SPARSEWEIGHTSENTRY']._serialized_start=353
  _globals['_HYBRIDEMBEDDING_SPARSEWEIGHTSENTRY']._serialized_end=405
  _globals['_EMBEDDINGSERVICE']._serialized_start=775
  _globals['_EMBEDDINGSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
